<!-- pages/publication/createPublication.vue -->
<template>
  <div class="create-publication">
    <nav class="navbar">
      <div class="navbar-brand">
        <h1>Create Publication</h1>
      </div>
      <div class="navbar-actions">
        <button @click="goBack" class="btn-nav">Back</button>
        <button @click="goToProfile" class="btn-nav">Profile</button>
        <button @click="goLogout" class="btn-logout">Logout</button>
      </div>
    </nav>

    <div class="form-container">
      <form @submit.prevent="handleSubmit" class="pub-form" enctype="multipart/form-data">
        <div class="form-row">
          <label>Title *</label>
          <input v-model="form.title" type="text" required />
        </div>

        <div class="form-row">
          <label>Summary</label>
          <textarea v-model="form.summary" rows="3" placeholder="Optional — if empty, summary may be generated by backend"></textarea>
        </div>

        <div class="form-row">
          <label>Scientific Area *</label>
          <select v-model="form.scientificArea" required>
            <option disabled value="">Select area</option>
            <option value="COMPUTER_SCIENCE">COMPUTER_SCIENCE</option>
            <option value="BIOLOGY">BIOLOGY</option>
            <option value="CHEMISTRY">CHEMISTRY</option>
            <option value="PHYSICS">PHYSICS</option>
            <option value="MATHEMATICS">MATHEMATICS</option>
            <option value="ENGINEERING">ENGINEERING</option>
            <option value="ENVIRONMENTAL_SCIENCE">ENVIRONMENTAL_SCIENCE</option>
            <option value="SOCIAL_SCIENCES">SOCIAL_SCIENCES</option>
            <option value="HUMANITIES">HUMANITIES</option>
          </select>
        </div>

        <div class="form-row">
          <label>Publication Date *</label>
          <input v-model="form.publicationDate" type="date" required />
        </div>

        <div class="form-row">
          <label>Authors (comma separated)</label>
          <input v-model="form.authors" placeholder="Alice,Bob,Charlie" />
        </div>

        <div class="form-row">
          <label>Tags</label>
          <div class="tags-list">
            <button
              v-for="tag in availableTags"
              :key="tag.id"
              type="button"
              @click="toggleTag(tag.id)"
              :class="['tag-chip', { active: selectedTags.includes(tag.id) }]"
            >
              {{ tag.name }}
              <span v-if="selectedTags.includes(tag.id)" class="check-icon">✓</span>
            </button>
          </div>
        </div>

        <div class="form-row">
          <label>File (PDF)</label>
          <input ref="fileInput" type="file" accept=".pdf" />
        </div>

        <div class="form-actions">
          <button type="submit" :disabled="submitting" class="btn-submit">
            {{ submitting ? 'Submitting...' : 'Create Publication' }}
          </button>
          <button type="button" @click="resetForm" class="btn-reset">Reset</button>
        </div>

        <div v-if="error" class="error">{{ error }}</div>
        <div v-if="success" class="success">{{ success }}</div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { usePublicationStore } from '~/stores/publication-store'
import { useTagStore } from '~/stores/tag-store'
import { useAuthStore } from '~/stores/auth-store'

const publicationStore = usePublicationStore()
const tagStore = useTagStore()
const authStore = useAuthStore()
const router = useRouter()

const form = ref({
  title: '',
  summary: '',
  scientificArea: '',
  publicationDate: '',
  authors: ''
})

const availableTags = ref([])
const selectedTags = ref([])
const submitting = ref(false)
const error = ref('')
const success = ref('')

const fileInput = ref(null)

onMounted(async () => {
  await loadTags()
})

async function loadTags() {
  try {
    availableTags.value = await tagStore.getAll()
  } catch (e) {
    console.error('Failed to load tags', e)
  }
}

function toggleTag(tagId) {
  const idx = selectedTags.value.indexOf(tagId)
  if (idx > -1) selectedTags.value.splice(idx, 1)
  else selectedTags.value.push(tagId)
}

function resetForm() {
  form.value = {
    title: '',
    summary: '',
    scientificArea: '',
    publicationDate: '',
    authors: ''
  }
  selectedTags.value = []
  error.value = ''
  success.value = ''
  if (fileInput.value) fileInput.value.value = null
}

function goBack() {
  router.back()
}

function goToProfile() {
  const username = authStore.user?.username || authStore.username
  if (username) router.push(`/users/${username}`)
}

function goLogout() {
  router.push('/auth/login')
}

async function handleSubmit() {
  error.value = ''
  success.value = ''
  if (!form.value.title || !form.value.scientificArea || !form.value.publicationDate) {
    error.value = 'Title, Scientific Area and Publication Date are required.'
    return
  }

  submitting.value = true

  try {
    const fd = new FormData()
    fd.append('title', form.value.title)
    fd.append('summary', form.value.summary || '')
    fd.append('scientificArea', form.value.scientificArea)
    // publicationDate must be yyyy-mm-dd
    fd.append('publicationDate', form.value.publicationDate)
    // authors as comma separated string
    if (form.value.authors && form.value.authors.trim() !== '') {
      fd.append('authors', form.value.authors)
    }
    
    if (selectedTags.value.length > 0) {
      fd.append('tagIds', selectedTags.value.join(','))
    }
    // file input
    const fileEl = fileInput.value
    if (fileEl && fileEl.files && fileEl.files[0]) {
      fd.append('file', fileEl.files[0])
    }

    
    const resp = await publicationStore.create(fd)

    
    const id = resp?.id || (resp?.data && resp.data.id)

    if (id) {
      success.value = 'Publication created successfully.'
    
      router.push(`/publication/searchPublications`)
    } else {
      // se backend devolveu processamento assíncrono (202) pode devolver message + id
      if (resp?.status === 202 && resp?.data?.id) {
        router.push(`/publication/searchPublications`)
      } else {
        success.value = 'Publication created. Check server response.'
        // se quiseres, podes mostrar resp (console) para debugging
        console.log('create response', resp)
      }
    }
  } catch (e) {
    console.error(e)
    error.value = e?.message || 'Failed to create publication'
  } finally {
    submitting.value = false
  }
}
</script>

<style scoped>
.create-publication {
  font-family: "Inter", sans-serif;
  padding: 20px;
  max-width: 900px;
  margin: 0 auto;
}

/* Reaproveitei estilos semelhantes aos da página de search */
.navbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 15px 0;
  margin-bottom: 20px;
  border-bottom: 2px solid #e0e0e0;
}

.navbar-brand h1 {
  margin: 0;
  color: #333;
  font-size: 22px;
}

.navbar-actions {
  display: flex;
  gap: 10px;
  align-items: center;
}

.btn-nav {
  background: transparent;
  color: #0077cc;
  border: 1px solid #0077cc;
  padding: 8px 12px;
  border-radius: 4px;
  cursor: pointer;
  font-weight: 500;
}

.btn-nav:hover {
  background: #0077cc;
  color: white;
}

.btn-logout {
  background: #dc3545;
  color: white;
  border: none;
  padding: 8px 12px;
  border-radius: 4px;
  cursor: pointer;
}

.btn-logout:hover {
  background: #c82333;
}

.form-container {
  background: white;
  padding: 18px;
  border-radius: 8px;
  box-shadow: 0 2px 6px rgba(0,0,0,0.05);
}

.pub-form {
  display: grid;
  gap: 12px;
}

.form-row {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.form-row label {
  font-size: 14px;
  color: #333;
  font-weight: 600;
}

.form-row input[type="text"],
.form-row input[type="date"],
.form-row textarea,
.form-row select {
  padding: 8px 10px;
  border: 1px solid #ddd;
  border-radius: 6px;
  font-size: 14px;
}

.tags-list {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.tag-chip {
  padding: 6px 10px;
  border-radius: 18px;
  border: 1px solid #ddd;
  background: white;
  cursor: pointer;
}

.tag-chip.active {
  background: #0077cc;
  color: white;
  border-color: #0077cc;
}

.form-actions {
  display: flex;
  gap: 12px;
  margin-top: 6px;
}

.btn-submit {
  padding: 10px 18px;
  background: #28a745;
  color: white;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 700;
}

.btn-reset {
  padding: 10px 16px;
  background: #f8f9fa;
  border: 1px solid #ddd;
  border-radius: 6px;
  cursor: pointer;
}

.error {
  margin-top: 10px;
  background: #fee;
  color: #c33;
  padding: 8px 12px;
  border-radius: 6px;
}

.success {
  margin-top: 10px;
  background: #eef9F0;
  color: #2d7a2d;
  padding: 8px 12px;
  border-radius: 6px;
}
</style>
