<!-- pages/publication/createPublication.vue -->
<template>
  <div class="create-publication">
    <nav class="navbar">
      <div class="navbar-brand">
        <h1>Create Publication</h1>
      </div>
      <div class="navbar-actions">
        <button @click="goBack" class="btn-nav">Back</button>
        <button @click="goToProfile" class="btn-nav">Profile</button>
        <button @click="goLogout" class="btn-logout">Logout</button>
      </div>
    </nav>

    <div class="form-container">
      <form @submit.prevent="handleSubmit" class="pub-form" enctype="multipart/form-data">
        <div class="form-section">
          <h2 class="section-title">Basic Information</h2>

          <div class="form-row">
            <label>Title *</label>
            <input v-model="form.title" type="text" required placeholder="Enter publication title" />
          </div>

          <div class="form-row">
            <label>Summary</label>
            <textarea
                v-model="form.summary"
                rows="5"
                placeholder="Optional — if empty, summary may be generated by AI from the uploaded document"
            ></textarea>
            <span class="field-hint">Leave empty for automatic AI-generated summary</span>
          </div>
        </div>

        <div class="form-section">
          <h2 class="section-title">Publication Details</h2>

          <div class="form-row-group">
            <div class="form-row">
              <label>Scientific Area *</label>
              <select v-model="form.scientificArea" required>
                <option disabled value="">Select scientific area</option>
                <option value="COMPUTER_SCIENCE">Computer Science</option>
                <option value="BIOLOGY">Biology</option>
                <option value="CHEMISTRY">Chemistry</option>
                <option value="PHYSICS">Physics</option>
                <option value="MATHEMATICS">Mathematics</option>
                <option value="ENGINEERING">Engineering</option>
                <option value="ENVIRONMENTAL_SCIENCE">Environmental Science</option>
                <option value="SOCIAL_SCIENCES">Social Sciences</option>
                <option value="HUMANITIES">Humanities</option>
              </select>
            </div>

            <div class="form-row">
              <label>Publication Date *</label>
              <input v-model="form.publicationDate" type="date" required />
            </div>
          </div>

          <div class="form-row">
            <label>Authors</label>
            <input
                v-model="form.authors"
                placeholder="Alice, Bob, Charlie (comma separated)"
            />
            <span class="field-hint">Separate multiple authors with commas</span>
          </div>
        </div>

        <div class="form-section">
          <h2 class="section-title">Tags</h2>
          <p class="section-description">Select relevant tags for this publication</p>

          <div v-if="availableTags.length === 0" class="no-tags-message">
            No tags available. You can add tags later.
          </div>
          <div v-else class="tags-container">
            <button
                v-for="tag in availableTags"
                :key="tag.id"
                type="button"
                @click="toggleTag(tag.id)"
                :class="['tag-chip', { active: selectedTags.includes(tag.id) }]"
            >
              {{ tag.name }}
              <span v-if="selectedTags.includes(tag.id)" class="check-icon">✓</span>
            </button>
          </div>
        </div>

        <div class="form-section">
          <h2 class="section-title">Document Upload</h2>
          <p class="section-description">Upload your publication document (PDF or ZIP)</p>

          <div class="file-upload-area">
            <input
                ref="fileInput"
                type="file"
                accept=".pdf,.zip"
                @change="handleFileChange"
                id="file-input"
            />
            <label for="file-input" class="file-upload-label">
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                <polyline points="17 8 12 3 7 8"></polyline>
                <line x1="12" y1="3" x2="12" y2="15"></line>
              </svg>
              <span class="file-upload-text">
                {{ selectedFileName || 'Click to upload or drag and drop' }}
              </span>
              <span class="file-upload-hint">PDF or ZIP (max 50MB)</span>
            </label>
          </div>
        </div>

        <div class="form-actions">
          <button type="submit" :disabled="submitting" class="btn-submit">
            <span v-if="submitting">
              <svg class="spinner" width="20" height="20" viewBox="0 0 24 24">
                <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none" opacity="0.25"/>
                <path d="M12 2a10 10 0 0 1 10 10" stroke="currentColor" stroke-width="4" fill="none"/>
              </svg>
              Submitting...
            </span>
            <span v-else>Create Publication</span>
          </button>
          <button type="button" @click="resetForm" class="btn-reset" :disabled="submitting">
            Reset Form
          </button>
        </div>

        <div v-if="error" class="message message-error">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10"></circle>
            <line x1="15" y1="9" x2="9" y2="15"></line>
            <line x1="9" y1="9" x2="15" y2="15"></line>
          </svg>
          {{ error }}
        </div>
        <div v-if="success" class="message message-success">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
            <polyline points="22 4 12 14.01 9 11.01"></polyline>
          </svg>
          {{ success }}
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { usePublicationStore } from '~/stores/publication-store'
import { useTagStore } from '~/stores/tag-store'
import { useAuthStore } from '~/stores/auth-store'

const publicationStore = usePublicationStore()
const tagStore = useTagStore()
const authStore = useAuthStore()
const router = useRouter()

const form = ref({
  title: '',
  summary: '',
  scientificArea: '',
  publicationDate: '',
  authors: ''
})

const availableTags = ref([])
const selectedTags = ref([])
const submitting = ref(false)
const error = ref('')
const success = ref('')
const selectedFileName = ref('')

const fileInput = ref(null)

onMounted(async () => {
  await loadTags()
})

async function loadTags() {
  try {
    availableTags.value = await tagStore.getAll()
  } catch (e) {
    console.error('Failed to load tags', e)
  }
}

function toggleTag(tagId) {
  const idx = selectedTags.value.indexOf(tagId)
  if (idx > -1) selectedTags.value.splice(idx, 1)
  else selectedTags.value.push(tagId)
}

function handleFileChange(event) {
  const file = event.target.files[0]
  if (file) {
    selectedFileName.value = file.name
  } else {
    selectedFileName.value = ''
  }
}

function resetForm() {
  form.value = {
    title: '',
    summary: '',
    scientificArea: '',
    publicationDate: '',
    authors: ''
  }
  selectedTags.value = []
  selectedFileName.value = ''
  error.value = ''
  success.value = ''
  if (fileInput.value) fileInput.value.value = null
}

function goBack() {
  router.back()
}

function goToProfile() {
  const username = authStore.user?.username || authStore.username
  if (username) router.push(`/users/${username}`)
}

function goLogout() {
  router.push('/auth/login')
}

async function handleSubmit() {
  error.value = ''
  success.value = ''

  if (!form.value.title || !form.value.scientificArea || !form.value.publicationDate) {
    error.value = 'Title, Scientific Area and Publication Date are required.'
    return
  }

  submitting.value = true

  try {
    const fd = new FormData()
    fd.append('title', form.value.title)
    fd.append('summary', form.value.summary || '')
    fd.append('scientificArea', form.value.scientificArea)
    fd.append('publicationDate', form.value.publicationDate)

    if (form.value.authors && form.value.authors.trim() !== '') {
      fd.append('authors', form.value.authors)
    }

    if (selectedTags.value.length > 0) {
      fd.append('tagIds', selectedTags.value.join(','))
    }

    const fileEl = fileInput.value
    if (fileEl && fileEl.files && fileEl.files[0]) {
      fd.append('file', fileEl.files[0])
    }

    const resp = await publicationStore.create(fd)
    const id = resp?.id || (resp?.data && resp.data.id)

    if (id) {
      success.value = 'Publication created successfully!'
      setTimeout(() => {
        router.push(`/publication/searchPublications`)
      }, 1500)
    } else {
      if (resp?.status === 202 && resp?.data?.id) {
        success.value = 'Publication created! Summary is being generated...'
        setTimeout(() => {
          router.push(`/publication/searchPublications`)
        }, 2000)
      } else {
        success.value = 'Publication created successfully!'
        console.log('create response', resp)
      }
    }
  } catch (e) {
    console.error(e)
    error.value = e?.message || 'Failed to create publication'
  } finally {
    submitting.value = false
  }
}
</script>

<style scoped>
.create-publication {
  font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  padding: 20px;
  max-width: 900px;
  margin: 0 auto;
  min-height: 100vh;
  background: #f5f7fa;
}

.navbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px 0;
  margin-bottom: 30px;
  background: white;
  border-radius: 12px;
  padding: 20px 30px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.navbar-brand h1 {
  margin: 0;
  color: #1a202c;
  font-size: 26px;
  font-weight: 700;
}

.navbar-actions {
  display: flex;
  gap: 12px;
  align-items: center;
}

.btn-nav {
  background: transparent;
  color: #0077cc;
  border: 1px solid #0077cc;
  padding: 10px 20px;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 500;
  font-size: 14px;
  transition: all 0.2s;
}

.btn-nav:hover {
  background: #0077cc;
  color: white;
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(0, 119, 204, 0.2);
}

.btn-logout {
  background: #dc3545;
  color: white;
  border: none;
  padding: 10px 20px;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 600;
  font-size: 14px;
  transition: all 0.2s;
}

.btn-logout:hover {
  background: #c82333;
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(220, 53, 69, 0.3);
}

.form-container {
  background: white;
  padding: 40px;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.pub-form {
  display: flex;
  flex-direction: column;
  gap: 32px;
}

.form-section {
  padding: 24px;
  background: #f8f9fa;
  border-radius: 10px;
  border: 1px solid #e9ecef;
}

.section-title {
  margin: 0 0 8px 0;
  color: #1a202c;
  font-size: 18px;
  font-weight: 700;
}

.section-description {
  margin: 0 0 20px 0;
  color: #6c757d;
  font-size: 14px;
}

.form-row {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-bottom: 20px;
}

.form-row:last-child {
  margin-bottom: 0;
}

.form-row-group {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
  margin-bottom: 20px;
}

.form-row label {
  font-size: 14px;
  color: #2d3748;
  font-weight: 600;
}

.form-row input[type="text"],
.form-row input[type="date"],
.form-row textarea,
.form-row select {
  padding: 12px 16px;
  border: 2px solid #e2e8f0;
  border-radius: 8px;
  font-size: 15px;
  font-family: inherit;
  transition: all 0.2s;
  background: white;
}

.form-row input:focus,
.form-row textarea:focus,
.form-row select:focus {
  outline: none;
  border-color: #0077cc;
  box-shadow: 0 0 0 3px rgba(0, 119, 204, 0.1);
}

.form-row textarea {
  resize: vertical;
  min-height: 120px;
  line-height: 1.6;
}

.field-hint {
  font-size: 13px;
  color: #6c757d;
  font-style: italic;
}

.no-tags-message {
  padding: 20px;
  text-align: center;
  color: #6c757d;
  font-style: italic;
}

.tags-container {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.tag-chip {
  padding: 10px 18px;
  border-radius: 24px;
  border: 2px solid #e2e8f0;
  background: white;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  transition: all 0.2s;
  display: flex;
  align-items: center;
  gap: 6px;
  color: #4a5568;
}

.tag-chip:hover {
  border-color: #0077cc;
  background: #f0f8ff;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 119, 204, 0.15);
}

.tag-chip.active {
  background: #0077cc;
  color: white;
  border-color: #0077cc;
  font-weight: 600;
}

.check-icon {
  font-weight: bold;
  font-size: 16px;
}

.file-upload-area {
  margin-top: 12px;
}

#file-input {
  display: none;
}

.file-upload-label {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 40px;
  border: 3px dashed #cbd5e0;
  border-radius: 12px;
  background: white;
  cursor: pointer;
  transition: all 0.3s;
  color: #4a5568;
}

.file-upload-label:hover {
  border-color: #0077cc;
  background: #f0f8ff;
}

.file-upload-label svg {
  color: #0077cc;
  margin-bottom: 12px;
}

.file-upload-text {
  font-size: 16px;
  font-weight: 600;
  color: #2d3748;
  margin-bottom: 4px;
}

.file-upload-hint {
  font-size: 13px;
  color: #718096;
}

.form-actions {
  display: flex;
  gap: 16px;
  padding-top: 12px;
  border-top: 2px solid #e9ecef;
}

.btn-submit {
  flex: 1;
  padding: 16px 32px;
  background: linear-gradient(135deg, #0077cc 0%, #005fa3 100%);
  color: white;
  border: none;
  border-radius: 10px;
  cursor: pointer;
  font-weight: 700;
  font-size: 16px;
  transition: all 0.3s;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  box-shadow: 0 4px 14px rgba(0, 119, 204, 0.3);
}

.btn-submit:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 6px 20px rgba(0, 119, 204, 0.4);
}

.btn-submit:disabled {
  opacity: 0.7;
  cursor: not-allowed;
  transform: none;
}

.spinner {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.btn-reset {
  padding: 16px 32px;
  background: white;
  color: #4a5568;
  border: 2px solid #e2e8f0;
  border-radius: 10px;
  cursor: pointer;
  font-weight: 600;
  font-size: 16px;
  transition: all 0.2s;
}

.btn-reset:hover:not(:disabled) {
  background: #f7fafc;
  border-color: #cbd5e0;
  transform: translateY(-1px);
}

.btn-reset:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* Messages */
.message {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 16px 20px;
  border-radius: 10px;
  font-size: 15px;
  font-weight: 500;
  margin-top: 20px;
}

.message svg {
  flex-shrink: 0;
}

.message-error {
  background: #fee;
  color: #c33;
  border: 2px solid #fcc;
}

.message-success {
  background: #eef9f0;
  color: #2d7a2d;
  border: 2px solid #c3e6cb;
}

/* Responsive */
@media (max-width: 768px) {
  .create-publication {
    padding: 15px;
  }

  .form-container {
    padding: 24px;
  }

  .navbar {
    flex-direction: column;
    gap: 15px;
    padding: 20px;
  }

  .navbar-actions {
    width: 100%;
    justify-content: center;
  }

  .form-row-group {
    grid-template-columns: 1fr;
  }

  .form-actions {
    flex-direction: column;
  }
}
</style>